rootDir: /tmp/cluster1/demo/person
server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 10005
  adminConnectors:
    - type: http
      port: 10081
messages:
  hello: Hello world!
  rootDir: /tmp
  name: cluster1
